# Generated by Django 5.2.6 on 2025-09-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_imagewithcontext_gallery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewithcontext',
            name='image',
            field=models.ImageField(upload_to='gallery1/'),
        ),
    ]
