# Generated by Django 5.2.6 on 2025-09-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_imagewithcontext_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewithcontext',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
