# Generated by Django 5.2.6 on 2025-09-14 12:57

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_imagewithcontext_date_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagewithcontext',
            old_name='date_created',
            new_name='created',
        ),
        migrations.AddField(
            model_name='gallery',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='creator_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_galery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagewithcontext',
            name='creatorName',
            field=models.CharField(default='NEMO NOBODY', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagewithcontext',
            name='gallery_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='imagewithcontext',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='imagewithcontext',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_to),
        ),
    ]
