# Generated by Django 5.2.6 on 2025-09-14 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_date_created_imagewithcontext_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewithcontext',
            name='gallery_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.gallery'),
        ),
    ]
