# Generated by Django 5.2.6 on 2025-09-14 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_imagewithcontext_gallery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewithcontext',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
