# Generated by Django 5.2.6 on 2025-09-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_gallery_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagewithcontext',
            old_name='creatorName',
            new_name='creator_name',
        ),
    ]
