# Generated by Django 5.2.6 on 2025-09-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_creatorname_imagewithcontext_creator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewithcontext',
            name='thumbnail_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
