# Generated by Django 5.2.6 on 2025-09-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_imagewithcontext_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagewithcontext',
            name='image',
        ),
        migrations.AddField(
            model_name='imagewithcontext',
            name='image_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
