# Generated by Django 5.2.6 on 2025-09-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_imagewithcontext_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageWithContext',
            new_name='ImageContext',
        ),
    ]
